name: gem_template
version: 0.1.0
authors:
  -
email:
homepage:
summary:
description:
dependencies:
  - active_wrapper
  - haml
  - lilypad
  - rack-flash
  - sinatra
development_dependencies:
  - cucumber
  - rspec
  - rack-test