gem_template:
  rake: =0.8.7
  rspec: =1.3.1
  default:
    active_wrapper: =0.3.4
    cucumber: =0.9.4
    haml: =3.0.24
    lilypad: =0.3.1
    rack-flash: =0.1.1
    rack-test: =0.5.6
    sinatra: =1.1.0